#!/usr/bin/env bash
. /usr/local/lib/cartenz-ui.sh
title "TROJAN MENU"

top; center_row "${B}${FG}>>> AKSI TROJAN <<<${NC}"; sep
items=(
  "${BLU}[${NC}${B}01${NC}${BLU}]${NC} Create Trojan"
  "${BLU}[${NC}${B}02${NC}${BLU}]${NC} Trial Trojan"
  "${BLU}[${NC}${B}03${NC}${BLU}]${NC} Renew Trojan"
  "${BLU}[${NC}${B}04${NC}${BLU}]${NC} Delete Trojan"
  "${BLU}[${NC}${B}05${NC}${BLU}]${NC} Check Login Trojan"
  "${BLU}[${NC}${B}06${NC}${BLU}]${NC} View Create Log"
  "${BLU}[${NC}${B}x ${NC}${BLU}]${NC} Kembali"
); grid_menu_auto items
bot; echo
read -rp "Pilih: " o
case "$o" in
  1|01) clear; add-tr ;;
  2|02) clear; trialtrojan ;;
  3|03) clear; renew-tr ;;
  4|04) clear; del-tr ;;
  5|05) clear; cek-tr ;;
  6|06) clear; ${PAGER:-less} /etc/log-create-trojan.log ;;
  x|X)  menu ;;
  *)    echo "Pilihan salah"; sleep 1; exec "$0" ;;
esac
