#!/usr/bin/env bash
. /usr/local/lib/cartenz-ui.sh
title "VLESS MENU"

top; center_row "${B}${FG}>>> AKSI VLESS <<<${NC}"; sep
items=(
  "${BLU}[${NC}${B}01${NC}${BLU}]${NC} Create Vless"
  "${BLU}[${NC}${B}02${NC}${BLU}]${NC} Trial Vless"
  "${BLU}[${NC}${B}03${NC}${BLU}]${NC} Renew Vless"
  "${BLU}[${NC}${B}04${NC}${BLU}]${NC} Delete Vless"
  "${BLU}[${NC}${B}05${NC}${BLU}]${NC} Check Login Vless"
  "${BLU}[${NC}${B}06${NC}${BLU}]${NC} View Create Log"
  "${BLU}[${NC}${B}x ${NC}${BLU}]${NC} Kembali"
); grid_menu_auto items
bot; echo
read -rp "Pilih: " o
case "$o" in
  1|01) clear; add-vless ;;
  2|02) clear; trialvless ;;
  3|03) clear; renew-vless ;;
  4|04) clear; del-vless ;;
  5|05) clear; cek-vless ;;
  6|06) clear; ${PAGER:-less} /etc/log-create-vless.log ;;
  x|X)  menu ;;
  *)    echo "Pilihan salah"; sleep 1; exec "$0" ;;
esac
